CREATE TABLE IF NOT EXISTS Profiles (
   profileid      SERIAL PRIMARY KEY,
   firstname      VARCHAR(50),
   lastname       VARCHAR(50),
   nickname       VARCHAR(50),
   email          VARCHAR(100),
   address        VARCHAR(100),
   city           VARCHAR(100),
   state          VARCHAR(100),
   zip            NUMERIC(5),
   cellphone      VARCHAR(15),
   homephone      VARCHAR(15),
   birthday       VARCHAR(10),
   imageurl       VARCHAR(400),
   position       VARCHAR(20),
   permissions    VARCHAR(15),
   handbook       BOOLEAN,
   orangeneckerchief       BOOLEAN,
   thunderbirdneckerchief  BOOLEAN,
   active         BOOLEAN,
   adult          BOOLEAN,
   clientid       VARCHAR(50)
)
